// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './page.module.css';
import ClientProvider from './components/ClientProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ginko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the application in the ClientProvider */}
        <ClientProvider>
          <main className={styles.main}>
            <div className={styles.description}>
              <p>
                A long way to learn
                <code className={styles.code}> Node, React, GraphQL, TypeScript, docker ...</code>
              </p>
            </div>
            {children}
          </main>
        </ClientProvider>
      </body>
    </html>
  );
}
